apiVersion: v1
data:
  app-config.production.yaml: |
    app:
      baseUrl: http://localhost:7007

    backend:
      baseUrl: http://localhost:7007
      listen:
        port: 7007
        host: 0.0.0.0
      database:
        client: pg
        connection:
          host: postgres
          port: 5432
          user: backstage
          password: backstage
          database: backstage

    catalog:
      rules:
        - allow: [Component, System, API, Group, User, Resource, Location]
      locations:
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    auth:
      environment: development
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true

    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
        - type: config
          clusters:
            - url: https://kubernetes.default.svc
              name: backstage-lab
              authProvider: serviceAccount
              skipTLSVerify: true
              serviceAccountToken: ${K8S_SA_TOKEN}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"app-config.production.yaml":"app:\n  baseUrl: http://localhost:7007\n\nbackend:\n  baseUrl: http://localhost:7007\n  listen:\n    port: 7007\n    host: 0.0.0.0\n  database:\n    client: pg\n    connection:\n      host: postgres\n      port: 5432\n      user: backstage\n      password: backstage\n      database: backstage\n\ncatalog:\n  rules:\n    - allow: [Component, System, API, Group, User, Resource, Location]\n  locations:\n    - type: url\n      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml\n\nauth:\n  environment: development\n  providers:\n    guest:\n      dangerouslyAllowOutsideDevelopment: true\n\nkubernetes:\n  serviceLocatorMethod:\n    type: multiTenant\n  clusterLocatorMethods:\n    - type: config\n      clusters:\n        - url: https://kubernetes.default.svc\n          name: backstage-lab\n          authProvider: serviceAccount\n          skipTLSVerify: true\n          serviceAccountToken: ${K8S_SA_TOKEN}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"backstage-config","namespace":"backstage"}}
  creationTimestamp: "2026-05-17T14:47:18Z"
  name: backstage-config
  namespace: backstage
  resourceVersion: "20829"
  uid: d3d187ef-0b73-4954-b1f9-e5d2670697b8
