apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    backstage.io/kubernetes-id: backstage
spec:
  type: service
  lifecycle: production
  owner: user:guest
